name: Go-test
on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test ./...
